<?php
error_reporting(0);
ini_set('display_errors', 0);
include 'assets/lang/lang.php';
$currentPath = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
$disableAnalytics = true;
?>

<!DOCTYPE html>
<html lang="<?= $text['lang'] ?>">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><?= $text['time-title-2'] ?></title>
    <meta name="description" content="<?= $text['time-title'] ?>">
    <meta property="og:title" content="<?= $text['time'] ?>">
    <meta property="og:description" content="<?= $text['time-title'] ?>">
    <?php include 'assets/inc/head.php' ?>
    <link rel="stylesheet" type="text/css" href="assets/css/time.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.4.0/css/all.min.css" />
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Droid+Sans:wght@400&display=swap">
</head>
<body>
    <?php include 'assets/inc/help-modal.php'; ?>
    <button id="toggle-button" title="<?= $text['time-settings'] ?>">
        <div class="time-menu">
            <i class="fa-solid fa-gear" id="toggle-icon"></i>
        </div>
    </button>

    <button id="full-button" title="<?= $text['time-fullscreen'] ?>">
        <div class="time-menu">
            <i class="fa-solid fa-maximize" id="full-icon"></i>
        </div>
    </button>

    <button id="local-timezone-button" title="<?= $text['time-local-timezone'] ?>">
        <div class="time-menu">
            <i class="fa-solid fa-location-dot" id="local-timezone-icon"></i>
        </div>
    </button>

    <div class="timezone" id="timezone-container">
        <input type="text" id="timezone-search" placeholder="<?= $text['time-search'] ?>">
        <select id="timezone-selector" title="<?= $text['time-select-timezone'] ?>">
            <!-- The options will be dynamically generated by the script -->
        </select>
    </div>

    <div id="time">00:00:00</div><br>
    <div id="time-control"></div>

    <script>
        const translations = {
            timeIs: <?= json_encode($text['time-is-title']) ?>,
            timeWaiting: <?= json_encode($text['time-waiting']) ?>,
            timeSyncOk: <?= json_encode($text['time-sync-ok']) ?>,
            timeSyncError: <?= json_encode($text['time-sync-error']) ?>,
            timeSeconds: <?= json_encode($text['time-seconds']) ?>,
        };
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/luxon/3.2.0/luxon.min.js"></script>
    <script type="text/javascript" src="assets/js/time.js"></script>
</body>
</html>